# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rainbow', git: 'https://github.com/sickill/rainbow.git'
gem 'relaxed-rubocop'
gem 'rubocop'
gem 'rubocop-performance'

gem 'awesome_print'

gem 'puma'
gem 'shotgun'
gem 'sinatra'

gem 'colored2'
gem 'rack-test'
gem 'rake'
gem 'rspec'
gem 'rspec-its'