#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

export TERM="linux"

setup_bazelrc() {
  cat > buildkite.bazelrc <<EOF
build --worker_verbose --verbose_failures
EOF

  cat >> .bazelignore <<EOF
frontend/
EOF

  cat >> .gitignore <<EOF
.bazelignore
EOF
}

main() {
  setup_bazelrc
}

main "$@"