#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

export TERM="linux"

setup() {
  cat > buildkite.bazelrc <<EOF
build --worker_verbose --verbose_failures
EOF
}

main() {
  setup
}

main "$@"