java_library(
    name = "search",
    srcs = ["EditDistanceRanking.java"],
    visibility = ["//store-api:__subpackages__"],
    deps = [
        "//store-api/src/main/java/com/book/store/api/models",
    ],
)
